on: pull_request

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: build
      run: yarn --prod
    - name: bump version and merge it on develop
      uses: ./
      with:
        base-branch: master
        head-branch: pull-request-test
        github-token: ${{secrets.GITHUB_TOKEN}}
